### ISSUE TITLE
I can not install or update from v0.2.0 to v.0.23

### ISSUE THREAD

**Issue by chaoshengt** [wiheto/teneto#1]
Dear  @wiheto :
       I can not install or update from v0.2.0 to v.0.23, when I do it by "pip install teneto -U", it mentioned that some wrong in my computer. Thank you :)
![qq 20180204094005](https://user-images.githubusercontent.com/7035642/35773496-781a24da-098f-11e8-9308-22be37a15134.png)

**Comment by wiheto** [comment]
Seems like an error with the data that’s now included and windows paths (only tested on Linux). I’ll try and push a solution soon (probabaly tomorrow cause I currently am a little busy moving house/country). Sorry for the inconvenience!

**Comment by wiheto** [comment]
@chaoshengt this might be fixed now. Does it work for you?  If not, I have a few other alternatives (sorry, currently unable to test)

**Comment by chaoshengt** [comment]
@wiheto thank you, I tried it, but, it seems.........not works~~~
![11](https://user-images.githubusercontent.com/7035642/35774028-dcfefc72-099e-11e8-8dfe-24458dba1609.png)
![12](https://user-images.githubusercontent.com/7035642/35774029-dd3c86dc-099e-11e8-972f-9147c4ed6b10.png)
![13](https://user-images.githubusercontent.com/7035642/35774030-dd75a69c-099e-11e8-9b96-4def9ed3ff94.png)
![14](https://user-images.githubusercontent.com/7035642/35774031-ddaf6224-099e-11e8-9e5f-5604c9e133da.png)

**Comment by wiheto** [comment]
Ok. Try the following: 

`pip install distutils -U`
`pip install teneto==0.2.3`

If that does not work, I'll sit down with this tomorrow and test the solution.

**Comment by chaoshengt** [comment]
@wiheto however, I can install it by the command `python setup.py install` when I download it 
thank you

**Comment by chaoshengt** [comment]
@wiheto It works. Thank you @wiheto , I love your package very much!!!!

**Comment by wiheto** [comment]
Great! 

Happy that you like it!
