### ISSUE TITLE
change color for nodes in slice-plot

### ISSUE THREAD

**Issue by granitz** [wiheto/teneto#18]
Using nodekwargs to change colors for ax.scatter with temporal community leads to double assignment of color.

for example: 
ax = tnet.plot(plottype='slice_plot',ax=ax,cmap=plt.get_cmap("jet"),nodekwargs={'c':temp_community}) returns "scatter() got multiple values for keyword argument 'c'"
Here temp_community is node,time

**Comment by granitz** [comment]
for example: 
ax = tnet.plot(plottype='slice_plot',ax=ax,cmap=plt.get_cmap("jet"),nodekwargs={'c':temp_community}) returns "scatter() got multiple values for keyword argument 'c'"
Here temp_community is node,time

**Comment by wiheto** [comment]
Should be fixed in #19

**Comment by wiheto** [comment]
Or... since temp_community is node, time.... this won't actually be fixed. I need to add a community input argument that assigns the ax.scatter(...c=temp_community[:,t]) at each time-point. 

I'm on it.

**Comment by wiheto** [comment]
0.4.3 should have this fixed.

**Comment by wiheto** [comment]
Could you confirm it works once you have updated.

**Comment by granitz** [comment]
Perfect. That solved it!
