### ISSUE TITLE
Hi, some thing need update

### ISSUE THREAD

**Issue by chaoshengt** [wiheto/teneto#2]
dear @wiheto , I run the new teneto(0.2.4), I think some  little bugs need update, the information of the version and the example of the teneto.  :)
 
![plot_1](https://user-images.githubusercontent.com/7035642/35798028-8f12d570-0a9c-11e8-9774-b0168c540d64.png)
![v_1](https://user-images.githubusercontent.com/7035642/35798031-8f740930-0a9c-11e8-85b3-2fa5e055c1b3.png)

**Comment by wiheto** [comment]
Hey! 

I simply forgot to update the version number there (already fixed on next release).

I’m currently writing a much longer updated tutorial. Hopefully it is released in the next few weeks. 

The documentation within each function should be up to date (calling via help)

**Comment by chaoshengt** [comment]
@wiheto nice!  I will recommend your package to my friends, :+1:

**Comment by wiheto** [comment]
So the new examples/tutorials are getting released over the next week. Closing this issue now.
