### ISSUE TITLE
I can not update teneto

### ISSUE THREAD

**Issue by chaoshengt** [wiheto/teneto#3]
@wiheto , I can not update teneto, some bugs need fix. :)
![qq 20180223114630](https://user-images.githubusercontent.com/7035642/36576918-d6715400-188e-11e8-80a1-fc1bfb6f903d.jpg)

**Comment by wiheto** [comment]
Hi there. I need a little more info. Are you updating via pip or via github? 

i.e. `pip install teneto -U` or `pip install ./path/to/teneto teneto -U `

**Comment by chaoshengt** [comment]
@wiheto I updated teneto via `pip install teneto -U`    :)
![2018-02-23_213855](https://user-images.githubusercontent.com/7035642/36596861-19afe3fa-18e2-11e8-9a8d-1eb83a6c1e75.png)

**Comment by chaoshengt** [comment]
@wiheto I install teneto0.2.5 via `python setup.py build`,the info follows:
![2018-02-25_170246](https://user-images.githubusercontent.com/7035642/36639729-f9463ef8-1a4d-11e8-9941-653cd2302a79.png)

**Comment by wiheto** [comment]
I've placed 0.2.5 onto pypi and I think I've removed the error in the comment above. So try `pip install -U teneto`. Sorry about this.

**Comment by chaoshengt** [comment]
@wiheto。Thank you very much for your hard work！
