### ISSUE TITLE
can't run make_parcellation 

### ISSUE THREAD

**Issue by granitz** [wiheto/teneto#34]
tnet.make_parcellation(parcellation,removeconfounds=True,parc_type='region',parc_params=nilearn_params)

No (static) network community file found.
Process Process-12:
Traceback (most recent call last):
  File "/disk2/home/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/disk2/home/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/disk2/home/anaconda3/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/disk2/home/anaconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/disk2/home/anaconda3/lib/python3.6/site-packages/bids/layout/core.py", line 278, in __getattr__
    if attr in self.entities:
  File "/disk2/home/anaconda3/lib/python3.6/site-packages/bids/layout/core.py", line 278, in __getattr__
    if attr in self.entities:
  File "/disk2/home/anaconda3/lib/python3.6/site-packages/bids/layout/core.py", line 278, in __getattr__
    if attr in self.entities:
  [Previous line repeated 986 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-204-804b5f6d7d79> in <module>()
----> 1 tnet.make_parcellation(parcellation,removeconfounds=True,parc_type='region',parc_params=nilearn_params)
      2 

~/anaconda3/lib/python3.6/site-packages/teneto/classes/bids.py in make_parcellation(self, parcellation, parc_type, parc_params, network, update_pipeline, removeconfounds, tag, njobs, clean_params)
    863                                    parc_name, parc_type, parc_params) for i, f in enumerate(files)}
    864             for j in as_completed(job):
--> 865                 j.result()
    866 
    867         if update_pipeline == True:

~/anaconda3/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

~/anaconda3/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by granitz** [comment]
Instead of running ProcessPoolExecutor i did:
for i,f in enumerate(files):
          self._run_make_parcellation(f,i,tag,parcellation,parc_name,parc_type,parc_params)

**Comment by granitz** [comment]
Actually, Now When I run make_parcellation I get BrokenProcessPool 
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by wiheto** [comment]
Could you print the entire error that’s a above that’s above the brokenprocess. 

So I’m looking into this soon. Could you some info regarding how you are running this (locally on computer, on a HPC with singularity)? 

It’s most likely some legacy issues when I updated to be more compliant with bids derivatives in December.

**Comment by granitz** [comment]
Using this on Ubuntu x86_64. 

/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py:844: DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.
  params = attr.ib(convert=attr.converters.optional(tuple))
No (static) network community file found.
Process Process-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/anaconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/anaconda3/lib/python3.6/site-packages/bids/layout/core.py", line 278, in __getattr__
    if attr in self.entities:
  File "/anaconda3/lib/python3.6/site-packages/bids/layout/core.py", line 278, in __getattr__
    if attr in self.entities:
  File "/anaconda3/lib/python3.6/site-packages/bids/layout/core.py", line 278, in __getattr__
    if attr in self.entities:
  [Previous line repeated 986 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-2-9c78d9ceb2ab> in <module>()
----> 1 tnet.make_parcellation(parcellation,removeconfounds=True,parc_type='region',njobs=1,parc_params=nilearn_params)
      2 

~/anaconda3/lib/python3.6/site-packages/teneto/classes/bids.py** in make_parcellation(self, parcellation, parc_type, parc_params, network, update_pipeline, removeconfounds, tag, njobs, clean_params)
    863                                    parc_name, parc_type, parc_params) for i, f in enumerate(files)}
    864             for j in as_completed(job):
--> 865                 print(j.result())
    866 
    867         if update_pipeline == True:

~/anaconda3/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

~/anaconda3/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by wiheto** [comment]
What version is this? I can't see: 

```
864 for j in as_completed(job):
--> 865 print(j.result())
```

in the current version of teneto

**Comment by granitz** [comment]
> What version is this? I can't see:
> 
> ```
> 864 for j in as_completed(job):
> --> 865 print(j.result())
> ```
> in the current version of teneto

That was added by me when attempting to solve the problem (using version 0.4.3)

**Comment by wiheto** [comment]
If I’m understanding you correctly, please print the errors when you haven’t changed the code. Your change seems to be creating an error. 

/William

**Comment by wiheto** [comment]
Can you run the following code: 

```
tnet = teneto.TenetoBIDS(teneto.__path__[0] + '/data/testdata/dummybids/', pipeline='fmriprep', bids_suffix='preproc', bids_tags={'sub': '001', 'task': 'a', 'run': 'alpha'}, raw_data_exists=False)
tnet.make_parcellation('gordon2014_333')
tnet.load_data('parcellation')
```

**Comment by wiheto** [comment]
Also what is parcellation in your code?

**Comment by granitz** [comment]
> Can you run the following code:
> 
> ```
> tnet = teneto.TenetoBIDS(teneto.__path__[0] + '/data/testdata/dummybids/', pipeline='fmriprep', bids_suffix='preproc', bids_tags={'sub': '001', 'task': 'a', 'run': 'alpha'}, raw_data_exists=False)
> tnet.make_parcellation('gordon2014_333')
> tnet.load_data('parcellation')
> ```

It worked when I ran this. I still got the error BrokenProcessPool when I ran it similarly with my data instead, but it didn't work with raw_data_exist argument (there was an error in row 432 in utils.bids). The problem was removed when I deleted two empty folders (logs, reports) in the bids folder. Then the make_parcellation worked just fine (using Shaefer).

**Comment by wiheto** [comment]
looks like it is a pybids error. We'll do better pydbids integrations soon. 

But things are ok now? Can I close this issue?

**Comment by granitz** [comment]
It works fine now, thank you!

**Comment by wiheto** [comment]
So the reason for the BIDS validator error was (I think recent) update to pybids where non-BIDS directories throw an error. This may have been the reason for logs/reports throwing an error as they were empty. 

You can make a .bidsignore file to ignore these files.
