### ISSUE TITLE
error in params to make_parcellation

### ISSUE THREAD

**Issue by granitz** [wiheto/teneto#35]
When I run make_parcellation I get the following error which seems to be removed when I comment 'sidecar'.  

~/anaconda3/lib/python3.6/site-packages/teneto/classes/bids.py in make_parcellation(self, parcellation, parc_type, parc_params, network, update_pipeline, removeconfounds, tag, njobs, clean_params)
    859 
    860         for i,f in enumerate(files):
--> 861             self._run_make_parcellation(f,i,tag,parcellation,parc_name,parc_type,parc_params)
    862 
    863         if update_pipeline == True:

~/anaconda3/lib/python3.6/site-packages/teneto/classes/bids.py in _run_make_parcellation(self, f, i, tag, parcellation, parc_name, parc_type, parc_params)
    878             fsave, tag, 'parcellation', 'roi')
    879         roi = teneto.utils.make_parcellation(
--> 880             f, parcellation, parc_type, parc_params)
    881         # Make data node,time
    882         roi = roi.transpose()

~/anaconda3/lib/python3.6/site-packages/teneto/utils/utils.py in make_parcellation(data_path, parcellation, parc_type, parc_params)
    863     if parc_type == 'sphere':
    864         parcellation = load_parcellation_coords(parcellation)
--> 865         seed = NiftiSpheresMasker(np.array(parcellation), **parc_params)
    866         data = seed.fit_transform(data_path)
    867     elif parc_type == 'region':

TypeError: __init__() got an unexpected keyword argument 'description'

**Comment by wiheto** [comment]
What are you passing in parc_params when this error occurs?

**Comment by granitz** [comment]
These are the params:
nilearn_params = {'standardize': True,'low_pass': 0.1,'high_pass': 0.01,'t_r':2.396}

**Comment by wiheto** [comment]
Could you please explain what “removing sidecar” means. Because  the error you paste has nothing about sidecar in it.

**Comment by wiheto** [comment]
This seems to be solved now, right?

**Comment by granitz** [comment]
Yes, this is resolved now, thank you!

**Comment by wiheto** [comment]
Great!
