### ISSUE TITLE
Error during derive TVC possible related to confounds report

### ISSUE THREAD

**Issue by granitz** [wiheto/teneto#54]
Hey,
I got the following error:
I had selected confounds_report=True. The tvc files where generated.

.../lib/python3.6/site-packages/teneto/classes/bids.py in derive_temporalnetwork(self, params, update_pipeline, tag, njobs, confound_corr_report)
    246                 dfc_df_z = (dfc_df - dfc_df.mean())
    247                 df_z = (df - df.mean())
--> 248                 R_df = dfc_df_z.T.dot(df_z).div(len(dfc_df)).div(
    249                     df_z.std(ddof=0)).div(dfc_df_z.std(ddof=0), axis=0)
    250                 description = R_df.describe().transpose().to_html()

.../lib/python3.6/site-packages/pandas/core/frame.py in dot(self, other)
   1076             common = self.columns.union(other.index)
   1077             if len(common) > len(self.columns) or len(common) > len(other.index):
-> 1078                 raise ValueError("matrices are not aligned")
   1079 
   1080             left = self.reindex(columns=common, copy=False)

**Comment by wiheto** [comment]
This is a known error which should be fixed with the upcoming release of 0.5.0 where all the bids stuff is rewritten. For now, confounds_report=False is the only thing to be done here.
