### ISSUE TITLE
Query about compatible data preprocessing pipeline

### ISSUE THREAD

**Issue by vatika** [wiheto/teneto#7]
I am using data from ABIDE Preprocessed Initiative (C-PAC pipeline) as input to the derive function and using Fisher and Box-Cox transformation to normalize the derived graphlet.
However I am getting a warning saying that Box-Cox is returning edges with uniform values through time. Could this be due to the preprocessing strategy or the number of time points (~120 timepoints, 2 TR)?

**Comment by wiheto** [comment]
Which method are you using? 

From my experience, the box cox usually works for sliding window methods but can make uniform edges with other methods (especially jackknife).

Rule of thumb: If uniform edges are being returned, then the box cox is an inappropriate post processing method. So I’d omit that step.

**Comment by vatika** [comment]
I was using euclidean distance method.

**Comment by wiheto** [comment]
Yeah. That is a method where the box-cox can fail for some edges. At some point I want to see which edges fail and see if these are meaningful or nosey edges. But that’s on a todo list. 

So I would stick with just a fisher transform. I’ll update the documentation later today for postpro to say that the box cox is recomended for the sliding window methods.

**Comment by wiheto** [comment]
Closing this issue, as it appears to have been answered.
