### ISSUE TITLE
Speed up the shortest path calculation speed

### ISSUE THREAD

**Issue by ashaghal** [wiheto/teneto#80]
Hi, I ran into an issue in using the shortest path calculation in large networks with lots of nodes and I was wondering if there is any way we can speed up the calculation speed? and if this is going to be fixed in the next versions how long do you think does it take?

**Comment by wiheto** [comment]
Whenever I get the time to improve teneto I will, unfortunately I have been swamped all year, unable to do it in my spare time, and teneto is not currently supported by any research grant (although I am trying to fix this).

This is a known issue. See #74
