### ISSUE TITLE
Inconsistency when plotting slice plot a temporal network

### ISSUE THREAD

**Issue by balandongiv** [wiheto/teneto#83]
When  ploting a temporal network using `.plot`, I notice neighboring interaction were not properly connected.

Below are the plot produced by `teneto` plot
![ori_gtheory](https://user-images.githubusercontent.com/22090092/133565400-5fb08b81-686c-45df-b451-d7b47f7a4d57.jpg)

The red line indicate where connection should exist. Specifically, at slice 2,3,4
![file_gtheor](https://user-images.githubusercontent.com/22090092/133565077-ee2227f7-224a-4565-892d-3d15a7324b1c.jpg)

This issue can be replicate with the code below.

For reproducibility, the connection array can be download via:
[link to array](https://drive.google.com/file/d/10A5YdL8jKqbjXnoEf_FXfVpBLBSm4mPw/view?usp=sharing)
```

import teneto
import matplotlib.pyplot as plt
g_arr=np.load('g_arr.npy')
plt.style.use('mpl20')
tnet = teneto.TemporalNetwork(from_array=g_arr)
ax = tnet.plot('slice_plot')
ax.scatter([0,0,0], [0,1,2], s=150, color='red', zorder=50)
plt.show()
```

**Comment by wiheto** [comment]
Hi! 

They are actually there but are being masked by the nodes. 

`teneto.plot.slice_plot(g_arr, nodesize=10)`

Sorry about his. Will try and make some improvement so this doesn't happen again by accident (e.g. by autoscaling nodesize).

**Comment by wiheto** [comment]
This is the resulting image I get

![Figure_4](https://user-images.githubusercontent.com/17345075/133585353-5b88360a-061b-4313-b2d2-e5ba71eaae4f.png)

**Comment by balandongiv** [comment]
Thanks for prompt reply.

May I know you plot this graph?

I Tried
`teneto.plot.slice_plot(g_arr, nodesize=10)`

But, the compiler return an error

> TypeError: slice_plot() missing 1 required positional argument: 'ax'

Amend the code to

`teneto.plot.slice_plot(g_arr, nodesize=10,ax=ax)`

Return an error of

> <AxesSubplot:xlabel='Time'>


Wheras, amending the code as below

```
import teneto
import matplotlib.pyplot as plt
# g_arr=np.load('g_arr.npy')
plt.style.use('mpl20')
tnet = teneto.TemporalNetwork(from_array=g_arr)
ax = tnet.plot('slice_plot',nodesize=10)
ax.scatter([0,0,0], [0,1,2], s=150, color='red', zorder=50)
plt.show()

```


produced inconsistent node size (refer slice no 1) as below

![amend_gt](https://user-images.githubusercontent.com/22090092/133622605-44bd16c0-c89d-4c57-921c-2ee250982d1f.jpg)

**Comment by wiheto** [comment]
Sorry, should have copy pasted what I did instead of just writing the code (incorrectly). This is what works for me

```python
import numpy as np
import teneto
import matplotlib.pyplot as plt
fig,ax = plt.subplots(1)
g_arr=np.load('g_arr.npy')
teneto.plot.slice_plot(g_arr, ax, nodesize=10)
fig.show()
 
```

**Comment by wiheto** [comment]
To fix your figure that you wrote above, you need to change:

ax.scatter([0,0,0], [0,1,2], s=150, color='red', zorder=50)

and change the size of the red scatter plots you are adding in manually

**Comment by balandongiv** [comment]
Thanks for the update @wiheto , really appreciate it
