### ISSUE TITLE
Minor wording error in what_is_tnt.rst

### ISSUE THREAD

**Issue by kepler471** [wiheto/teneto#90]
> Teneto is a python package that can **several quantify** temporal network measures (more are being added). It can also use methods from time-varying connectivity to derive connectivity estimate from time-series data.

should probably be

> Teneto is a python package that can **quantify several** temporal network measures (more are being added). It can also use methods from time-varying connectivity to derive connectivity estimate from time-series data.

**Comment by wiheto** [comment]
Merged!
